Repository fractal-academy/expenses-app, pull requests merged in 2021-01, with the labels that each got.

#28 added qonsoll/react-design and removed bootstrap
  .storybook/preview.js
  package.json
Labels: enhancement, good first issue, help wanted

#30 Fixed Modal buttons, props, add props description
  src/app/components/Lib/Modal/Modal.stories.js
  src/app/components/Lib/Modal/Modal.template.js
  src/app/components/Lib/Modal/__test__/Modal.test.js
  src/app/components/Lib/Modal/index.js
  src/app/components/index.js
Labels: good first issue

#36 add teamplate select and add PRIORITY
  src/app/components/Select/Select.stories.js
  src/app/components/Select/Select.template.js
  src/app/components/Select/__tests__/Select.test.js
  src/app/components/Select/index.js
  src/app/components/index.js
  src/app/constants/index.js
  src/app/constants/priority.js
  src/app/domains/Priority/components/select/PrioritySingleSelect/PrioritySingleSelect.template.js
  src/app/domains/Priority/components/select/PrioritySingleSelect/Select.style.js
  src/app/domains/Priority/components/views/PrioritySimpleView/PrioritySimpleView.stories.js
  src/app/domains/Priority/components/views/PrioritySimpleView/PrioritySimpleView.template.js
Labels: enhancement, good first issue
