Repository fractal-academy/expenses-app, pull requests merged in 2021-02, with the labels that each got.

#53 add purchased items list and purchased advanced view(list item)
  src/app/domains/Purchase/components/list/PurchaseList/PurchaseList.stories.js
  src/app/domains/Purchase/components/list/PurchaseList/PurchaseList.template.js
  src/app/domains/Purchase/components/list/PurchaseList/__test__/PurchaseList.test.js
  src/app/domains/Purchase/components/list/PurchaseList/index.js
  src/app/domains/Purchase/components/list/index.js
  src/app/domains/Purchase/components/views/PurchaseAdvancedView/PurchaseAdvancedView.template.js
  src/app/domains/Purchase/routes/PurchaseAll/PurchaseAll.layout.js
Labels: good first issue

#51 add DataRange with filters,fix filters,add statisticWallet
  package.json
  src/app/components/Lib/DateRange/DateRange.stories.js
  src/app/components/Lib/DateRange/DateRange.template.js
  src/app/components/Lib/DateRange/__test__/DateRange.test.js
  src/app/components/Lib/DateRange/index.js
  src/app/context/StatisticsContext/StatisticsContext.js
  src/app/context/StatisticsContext/StatisticsProvider.js
  src/app/context/StatisticsContext/hooks/useStatisticsContext.js
  src/app/context/StatisticsContext/index.js
  src/app/domains/Statistic/components/CollapseDateRange/CollapseDateRange.styles.js
  src/app/domains/Statistic/components/CollapseDateRange/CollapseDateRange.template.js
  src/app/domains/Statistic/components/CollapseDateRange/index.js
  src/app/domains/Statistic/components/CollapseWallet/CollapseWallet.styles.js
  src/app/domains/Statistic/components/CollapseWallet/CollapseWallet.template.js
  src/app/domains/Statistic/components/CollapseWallet/index.js
  src/app/domains/Statistic/components/FiltersWithCollapse/FiltersWithCollapse.template.js
  src/app/domains/Statistic/components/FiltersWithCollapse/index.js
  src/app/domains/Statistic/components/filters/StatisticAdvancedFilter/StatisticAdvancedFilter.stories.js
  src/app/domains/Statistic/components/filters/StatisticAdvancedFilter/StatisticAdvancedFilter.template.js
  src/app/domains/Statistic/components/filters/StatisticAdvancedFilter/__tests__/StatisticAdvancedFilter.test.js
  src/app/domains/Statistic/components/filters/StatisticAdvancedFilter/index.js
  src/app/domains/Statistic/components/filters/StatisticSimpleFilter/StatisticSimpleFilter.stories.js
  src/app/domains/Statistic/components/filters/StatisticSimpleFilter/StatisticSimpleFilter.style.js
  src/app/domains/Statistic/components/filters/StatisticSimpleFilter/StatisticSimpleFilter.template.js
  src/app/domains/Statistic/components/filters/StatisticSimpleFilter/__tests__/StatisticSimpleFilter.test.js
  src/app/domains/Statistic/components/filters/StatisticSimpleFilter/index.js
  src/app/domains/Statistic/components/filters/index.js
  src/app/domains/Statistic/components/views/StatisticAdvancedView/StatisticAdvancedView.template.js
  src/app/domains/Statistic/routes/StatisticAll/StatisticAll.layout.js
  src/app/styles/index.css
Labels: enhancement

#59 Add filter logic dima
  package.json
  src/app/context/StatisticsContext/StatisticsProvider.js
  src/app/domains/Statistic/components/views/StatisticAdvancedView/StatisticAdvancedView.template.js
Labels: enhancement

#73 Add filter logic dima
  src/app/components/Lib/DateRange/DateRange.template.js
  src/app/context/StatisticsContext/StatisticsProvider.js
  src/app/domains/Statistic/components/CollapseDateRange/CollapseDateRange.template.js
  src/app/domains/Statistic/components/CollapseWallet/CollapseWallet.template.js
  src/app/domains/Statistic/components/ListItemWithCollapse/ListItemWithCollapse.js
  src/app/domains/Statistic/components/ListItemWithCollapse/index.js
  src/app/domains/Statistic/components/MemberWallets/MemberWallets.js
  src/app/domains/Statistic/components/MemberWallets/index.js
  src/app/domains/Statistic/components/filters/StatisticSimpleFilter/StatisticSimpleFilter.template.js
  src/app/domains/Statistic/components/views/StatisticAdvancedView/StatisticAdvancedView.template.js
  src/app/domains/Statistic/components/views/StatisticAdvancedView/optionsForChart.js
  src/app/domains/Statistic/helpers/addWalletToArr.js
  src/app/domains/Statistic/helpers/filterDataForChart.js
  src/app/domains/Statistic/helpers/filterDataForStatisticWallet.js
  src/app/domains/Statistic/helpers/objectToArray.js
  src/app/domains/Statistic/helpers/parseDataToArray.js
  src/app/domains/Statistic/helpers/parseDataToObject.js
  src/app/domains/Statistic/helpers/rangeForFilterData.js
  src/app/domains/Statistic/helpers/uniqueItems.js
  src/app/domains/Statistic/routes/StatisticAll/StatisticAll.layout.js
Labels: good first issue

#90 Product db
  src/app/components/Lib/LoadingButton/LoadingButton.template.js
  src/app/components/Lib/Modal/Modal.template.js
  src/app/components/Lib/Select/Select.template.js
  src/app/components/Lib/Table/Table.styles.js
  src/app/components/Lib/Table/Table.template.js
  src/app/components/Lib/Toolbar/Toolbar.template.js
  src/app/components/Settings/Settings.template.js
  src/app/constants/collection.js
  src/app/constants/index.js
  src/app/constants/tableCells.js
  src/app/domains/Cart/components/table/CartTable.template.js
  src/app/domains/Cart/routes/CartAll/CartAll.layout.js
  src/app/domains/Cart/routes/CartEdit/CartEdit.layout.js
  src/app/domains/Cart/routes/CartShow/CartShow.layout.js
  src/app/domains/Category/components/select/CategorySingleSelect/CategorySingleSelect.template.js
  src/app/domains/Measure/components/combined/MeasureModalWithForm/MeasureModalWithForm.template.js
  src/app/domains/Measure/components/forms/MeasureSimpleForm/MeasureSimpleForm.template.js
  src/app/domains/Measure/components/select/MeasureSingleSelect/MeasureSingleSelect.template.js
  src/app/domains/Measure/components/select/MeasureSingleSelectWithCreate/MeasureSingleSelectWithCreate.js
  src/app/domains/Measure/components/views/MeasureSimpleView/MeasureSimpleView.template.js
  src/app/domains/Member/components/select/MemberSingleSelect/MemberSingleSelect.template.js
  src/app/domains/Product/components/combined/ProductCombinedForm/ProductCombinedForm.template.js
  src/app/domains/Product/components/forms/ProductAdvancedForm/ProductAdvancedForm.template.js
  src/app/domains/Product/components/forms/ProductSimpleForm/ProductSimpleForm.template.js
  src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.styles.js
  src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
  src/app/domains/Purchase/components/table/PurchaseTable.template.js
  src/app/domains/Purchase/components/table/index.js
  src/app/domains/Purchase/routes/PurchaseAll/PurchaseAll.layout.js
  src/app/domains/Purchase/routes/PurchaseShow/PurchaseShow.layout.js
  src/app/domains/RegularProduct/components/combined/RegularProductCombined/RegularProductCombined.template.js
  src/app/domains/RegularProduct/components/forms/RegularProductAdvancedForm/RegularProductAdvancedForm.template.js
  src/app/domains/RegularProduct/components/forms/RegularProductSimpleForm/RegularProductSimpleForm.template.js
  src/app/domains/RegularProduct/components/select/RegularProductSingleSelect/RegularProductSingleSelect.template.js
  src/app/domains/RegularProduct/components/table/RegularProductsTable/RegularProductsTable.template.js
  src/app/domains/RegularProduct/routes/RegularProductAll/RegularProductAll.layout.js
  src/app/domains/RegularProduct/routes/RegularProductEdit/RegularProductEdit.layout.js
  src/app/domains/RegularProduct/routes/RegularProductShow/RegularProductShow.layout.js
  src/app/domains/Wish/components/table/WishTable.template.js
  src/app/domains/Wish/routes/WishAll/WishAll.layout.js
  src/app/domains/Wish/routes/WishEdit/WishEdit.layout.js
  src/app/domains/Wish/routes/WishShow/WishShow.layout.js
Labels: enhancement, good first issue

#117 Rewriting logger and replace old logger in project
  src/app/domains/Cart/components/table/CartTable.template.js
  src/app/domains/Cart/routes/CartEdit/CartEdit.layout.js
  src/app/domains/Category/components/combined/CategoryCombined/CategoryCombined.template.js
  src/app/domains/Category/components/views/CategoryAdvancedView/CategoryAdvancedView.template.js
  src/app/domains/Color/components/select/ColorSingleSelect/ColorSingleSelect.template.js
  src/app/domains/Color/components/views/ColorSimpleView/ColorSimpleView.styles.js
  src/app/domains/Color/components/views/ColorSimpleView/ColorSimpleView.template.js
  src/app/domains/Comment/components/combined/list/CommentListWithAdd/CommentListWithAdd.template.js
  src/app/domains/Log/components/list/LogList/LogList.template.js
  src/app/domains/Log/components/views/LogAdvancedView/LogAdvancedView.template.js
  src/app/domains/Log/routes/LogAll/LogAll.layout.js
  src/app/domains/Measure/components/combined/MeasureModalWithForm/MeasureModalWithForm.template.js
  src/app/domains/Member/components/combined/MemberCombined/MemberCombined.template.js
  src/app/domains/Member/components/views/MemberAdvancedView/MemberAdvancedView.template.js
  src/app/domains/Member/routes/MemberEdit/MemberEdit.layout.js
  src/app/domains/Member/routes/MemberShow/MemberShow.layout.js
  src/app/domains/Product/components/combined/ProductCombinedForm/ProductCombinedForm.template.js
  src/app/domains/Product/components/views/ProductAdvancedView/ProductAdvancedView.template.js
  src/app/domains/RegularProduct/components/combined/RegularProductCombined/RegularProductCombined.template.js
  src/app/domains/RegularProduct/routes/RegularProductEdit/RegularProductEdit.layout.js
  src/app/domains/Wallet/components/combined/WalletCombined/WalletCombined.template.js
  src/app/domains/Wallet/components/views/WalletAdvancedView/WalletAdvancedView.template.js
  src/app/domains/Wish/components/table/WishTable.template.js
  src/app/domains/Wish/routes/WishEdit/WishEdit.layout.js
  src/app/utils/Logger.js
  src/app/utils/index.js
Labels: good first issue
